'use client';

/**
 * TopOne V3 - Skill-Based Design
 * 
 * Design System Generated by: ui-ux-pro-max
 * Components from: ui-component-library
 * 
 * DESIGN TOKENS:
 * - Pattern: Feature-Rich Showcase + Trust
 * - Style: Trust & Authority
 * - Primary: #0F172A (slate-900)
 * - Secondary: #334155 (slate-700)
 * - CTA: #0369A1 (sky-700)
 * - Background: #F8FAFC (slate-50)
 * - Text: #020617 (slate-950)
 * - Typography: Noto Serif TC + Noto Sans TC
 * 
 * COMPONENTS USED:
 * - heroes.md: Standard Hero (Left Content, Right Image)
 * - features.md: Feature Grid (Icon Cards), Split Content (Zig-Zag)
 * - stats.md: Stats Counter Row, Logo Grid
 * - products.md: Product Showcase (Featured), Product Grid Card
 */

import React from 'react';
import {
    CheckCircle,
    Shield,
    Zap,
    Globe,
    Award,
    Target,
    Settings,
    Phone,
    Mail,
    MapPin,
    ChevronRight,
    Download
} from 'lucide-react';

export default function TopOneV3Page() {
    const stats = [
        { value: '35+', label: 'Years Experience' },
        { value: '50+', label: 'Countries Exported' },
        { value: '5000+', label: 'Machines Installed' },
        { value: '24h', label: 'Service Response' },
    ];

    const features = [
        { icon: Target, title: 'High Precision', desc: 'Achieve 0.003mm tolerance with our advanced servo systems and rigid structures.' },
        { icon: Shield, title: 'Durability', desc: 'Meehanite cast iron construction with hand-scraped surfaces for lifetime accuracy.' },
        { icon: Zap, title: 'Speed', desc: '36m/min rapid traverse with optimized acceleration for maximum productivity.' },
        { icon: Globe, title: 'Global Support', desc: '24/7 remote diagnostics and local service partners in 50+ countries.' },
        { icon: Award, title: 'Certifications', desc: 'ISO 9001 certified with CE marking and Taiwan Excellence Award winner.' },
        { icon: Settings, title: 'Customization', desc: 'Full OEM/ODM capability to meet your unique manufacturing requirements.' },
    ];

    const products = [
        { series: 'Bed Mill', name: 'CNC-800', desc: 'Heavy-duty bed mill for large workpiece machining.', specs: ['Table: 1200x500mm', 'Spindle: 8000rpm'] },
        { series: 'Lathe', name: 'WL-500', desc: 'Alloy wheel lathe with diamond turning capability.', specs: ['Max Dia: 800mm', 'Accuracy: ±0.01mm'] },
        { series: 'Grinder', name: 'IG-200', desc: 'ID/OD grinder for precision internal geometries.', specs: ['Spindle: 60000rpm', 'Surface: Ra0.1'] },
    ];

    return (
        // DESIGN TOKEN: bg-[#F8FAFC] = slate-50
        <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">

            {/* ------------------------------------------------------------------ */}
            {/* NAVIGATION - Based on ui-component-library structure principles */}
            {/* ------------------------------------------------------------------ */}
            <nav className="fixed top-0 w-full z-50 bg-white/90 backdrop-blur-md border-b border-slate-200/50 shadow-sm">
                <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
                    {/* Logo */}
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-slate-900 text-white flex items-center justify-center font-bold text-lg rounded">
                            T1
                        </div>
                        <div>
                            <span className="text-lg font-bold text-slate-900 tracking-tight">TOP-ONE</span>
                            <span className="block text-[10px] text-slate-500 uppercase tracking-widest">Machinery</span>
                        </div>
                    </div>

                    {/* Menu */}
                    <div className="hidden md:flex items-center gap-8">
                        {['Products', 'Features', 'Industries', 'About', 'Contact'].map((item) => (
                            <a key={item} href={`#${item.toLowerCase()}`} className="text-sm font-medium text-slate-600 hover:text-sky-700 transition-colors cursor-pointer">
                                {item}
                            </a>
                        ))}
                    </div>

                    {/* CTA - DESIGN TOKEN: bg-[#0369A1] = sky-700 */}
                    <button className="hidden md:flex items-center gap-2 px-5 py-2.5 bg-sky-700 text-white font-semibold text-sm rounded hover:bg-sky-800 transition-colors shadow-md shadow-sky-700/20 cursor-pointer">
                        Get Quote <ChevronRight className="w-4 h-4" />
                    </button>
                </div>
            </nav>

            {/* ------------------------------------------------------------------ */}
            {/* HERO - Template: heroes.md > Standard Hero (Left Content, Right Image) */}
            {/* ------------------------------------------------------------------ */}
            <section className="relative bg-white overflow-hidden pt-24">
                <div className="max-w-7xl mx-auto">
                    <div className="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32">
                        {/* SVG Diagonal */}
                        <svg
                            className="hidden lg:block absolute right-0 inset-y-0 h-full w-48 text-white transform translate-x-1/2"
                            fill="currentColor"
                            viewBox="0 0 100 100"
                            preserveAspectRatio="none"
                        >
                            <polygon points="50,0 100,0 50,100 0,100" />
                        </svg>

                        <main className="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
                            <div className="sm:text-center lg:text-left">
                                {/* DESIGN TOKEN: text-sky-700 */}
                                <p className="text-base text-sky-700 font-semibold tracking-wide uppercase">
                                    Taiwan's CNC Leader Since 1988
                                </p>
                                <h1 className="mt-4 text-4xl tracking-tight font-extrabold text-slate-900 sm:text-5xl md:text-6xl">
                                    <span className="block xl:inline">Precision</span>{' '}
                                    <span className="block text-sky-700 xl:inline">Engineered</span>
                                </h1>
                                <p className="mt-3 text-base text-slate-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
                                    World-class CNC machining centers with uncompromising accuracy. Your trusted OEM/ODM partner for aerospace, automotive, and medical industries.
                                </p>
                                <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start gap-3">
                                    <div className="rounded-md shadow">
                                        <a href="#contact" className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-sky-700 hover:bg-sky-800 md:py-4 md:text-lg md:px-10 transition-colors cursor-pointer">
                                            Contact Sales
                                        </a>
                                    </div>
                                    <div className="mt-3 sm:mt-0 sm:ml-3">
                                        <a href="#products" className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-sky-700 bg-sky-100 hover:bg-sky-200 md:py-4 md:text-lg md:px-10 transition-colors cursor-pointer">
                                            View Products
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </main>
                    </div>
                </div>
                {/* Hero Image */}
                <div className="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
                    <img
                        className="h-56 w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full"
                        src="https://picsum.photos/seed/topone_hero_v3/1200/800"
                        alt="CNC Machining Center"
                    />
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* STATS - Template: stats.md > Stats Counter Row */}
            {/* ------------------------------------------------------------------ */}
            <section className="bg-slate-100 py-12 border-y border-slate-200">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
                        {stats.map((stat, i) => (
                            <div key={i} className="text-center group cursor-default">
                                {/* DESIGN TOKEN: text-sky-700 on hover */}
                                <p className="text-4xl font-bold text-slate-900 group-hover:text-sky-700 transition-colors mb-1">{stat.value}</p>
                                <p className="text-slate-600 font-medium">{stat.label}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* FEATURES - Template: features.md > Feature Grid (Icon Cards) */}
            {/* ------------------------------------------------------------------ */}
            <section id="features" className="py-20 bg-slate-50">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="text-center mb-16">
                        <p className="text-sky-700 font-semibold uppercase tracking-widest text-sm mb-2">Why Choose Us</p>
                        <h2 className="text-3xl md:text-4xl font-bold text-slate-900">Industry Leading Durability and Precision</h2>
                        <p className="mt-4 text-xl text-slate-500 max-w-2xl mx-auto">
                            Every TOP-ONE machine is built with decades of engineering expertise and a commitment to quality.
                        </p>
                    </div>
                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {features.map((feat, i) => (
                            <div key={i} className="bg-white p-8 rounded-lg shadow-sm border border-slate-100 hover:shadow-lg hover:border-sky-200 transition-all cursor-pointer group">
                                <div className="w-14 h-14 bg-sky-100 rounded-lg flex items-center justify-center mb-6 group-hover:bg-sky-700 transition-colors">
                                    <feat.icon className="w-7 h-7 text-sky-700 group-hover:text-white transition-colors" />
                                </div>
                                <h3 className="text-xl font-bold text-slate-900 mb-3 group-hover:text-sky-700 transition-colors">{feat.title}</h3>
                                <p className="text-slate-500 leading-relaxed">{feat.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* PRODUCT SHOWCASE - Template: products.md > Product Showcase (Featured) */}
            {/* ------------------------------------------------------------------ */}
            <section id="products" className="bg-slate-900 text-white py-24">
                <div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-16 items-center">
                    <div>
                        <div className="inline-block px-3 py-1 bg-sky-700 text-white text-xs font-bold rounded mb-4 uppercase tracking-wider">
                            Flagship Model
                        </div>
                        <h2 className="text-4xl md:text-5xl font-bold mb-6">CNC-500X Series</h2>
                        <p className="text-white/70 text-lg mb-8 leading-relaxed">
                            The most advanced 5-axis machining center in our lineup. Featuring AI-driven optimization, 30% faster processing, and designed for lights-out manufacturing.
                        </p>
                        <div className="grid grid-cols-3 gap-6 mb-10 border-t border-white/10 pt-8">
                            <div>
                                <div className="text-3xl font-bold text-sky-400">0.003</div>
                                <div className="text-sm text-white/50">mm Precision</div>
                            </div>
                            <div>
                                <div className="text-3xl font-bold text-sky-400">20,000</div>
                                <div className="text-sm text-white/50">RPM</div>
                            </div>
                            <div>
                                <div className="text-3xl font-bold text-sky-400">24/7</div>
                                <div className="text-sm text-white/50">Operation</div>
                            </div>
                        </div>
                        <button className="flex items-center gap-2 px-6 py-3 border border-white/30 rounded hover:bg-white hover:text-slate-900 transition-colors cursor-pointer font-medium">
                            <Download className="w-5 h-5" />
                            Download Brochure
                        </button>
                    </div>
                    <div className="relative hidden lg:block">
                        {/* Abstract Background Decoration */}
                        <div className="absolute -inset-10 bg-gradient-to-br from-sky-500/20 to-transparent rounded-full blur-3xl"></div>
                        <img
                            src="https://picsum.photos/seed/cnc_flagship_v3/800/700"
                            alt="CNC-500X"
                            className="relative z-10 w-full rounded-lg shadow-2xl"
                        />
                    </div>
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* PRODUCT GRID - Template: products.md > Product Grid Card (B2B Standard) */}
            {/* ------------------------------------------------------------------ */}
            <section className="py-20 bg-white">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="text-center mb-12">
                        <h2 className="text-3xl font-bold text-slate-900">Our Product Range</h2>
                        <p className="mt-4 text-xl text-slate-500">Explore our diverse lineup of CNC solutions.</p>
                    </div>
                    <div className="grid md:grid-cols-3 gap-8">
                        {products.map((product, i) => (
                            <div key={i} className="group bg-white border border-slate-200 rounded-lg overflow-hidden hover:border-sky-500 transition-colors cursor-pointer">
                                <div className="aspect-[4/3] bg-slate-100 relative overflow-hidden">
                                    <img
                                        src={`https://picsum.photos/seed/product_${product.series.toLowerCase()}/600/450`}
                                        alt={product.name}
                                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                                    />
                                    <div className="absolute top-2 right-2">
                                        <span className="px-2 py-1 bg-white/90 backdrop-blur text-[10px] uppercase font-bold text-slate-600 rounded">
                                            {product.series}
                                        </span>
                                    </div>
                                </div>
                                <div className="p-5">
                                    <h3 className="text-lg font-bold text-slate-900 mb-1 group-hover:text-sky-700 transition-colors">
                                        {product.name}
                                    </h3>
                                    <p className="text-sm text-slate-500 mb-4">{product.desc}</p>

                                    {/* Key Specs */}
                                    <ul className="space-y-2 mb-4">
                                        {product.specs.map((spec, j) => (
                                            <li key={j} className="flex items-center gap-2 text-xs text-slate-600">
                                                <CheckCircle className="w-4 h-4 text-sky-600" />
                                                {spec}
                                            </li>
                                        ))}
                                    </ul>

                                    <button className="w-full py-2.5 bg-slate-100 text-slate-700 font-medium text-sm rounded hover:bg-sky-700 hover:text-white transition-colors cursor-pointer">
                                        View Details
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* SPLIT CONTENT - Template: features.md > Split Content (Zig-Zag) */}
            {/* ------------------------------------------------------------------ */}
            <section className="py-24 bg-slate-50 overflow-hidden">
                <div className="max-w-7xl mx-auto px-6 space-y-24">
                    {/* Item 1: Text Left, Image Right */}
                    <div className="grid lg:grid-cols-2 gap-16 items-center">
                        <div>
                            <p className="text-sky-700 font-semibold uppercase tracking-widest text-sm mb-2">OEM / ODM Services</p>
                            <h3 className="text-3xl font-bold text-slate-900 mb-6">Custom Machine Solutions</h3>
                            <p className="text-lg text-slate-500 mb-8 leading-relaxed">
                                From concept to delivery, our engineering team works closely with you to design and manufacture machines tailored to your exact specifications. Full 3D modeling, FEA simulation, and prototype validation included.
                            </p>
                            <ul className="space-y-4">
                                {['Design & Engineering', 'Precision Casting', '5-Axis CNC Machining', 'Hand-Scraping Expertise', 'Quality Verification'].map((item, i) => (
                                    <li key={i} className="flex items-center gap-3">
                                        <CheckCircle className="w-5 h-5 text-sky-600 flex-shrink-0" />
                                        <span className="text-slate-700">{item}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                        <div className="relative">
                            <div className="absolute -inset-4 bg-sky-100 transform rotate-2 rounded-2xl"></div>
                            <img
                                src="https://picsum.photos/seed/oem_process_v3/800/600"
                                alt="OEM Process"
                                className="relative rounded-xl shadow-xl w-full"
                            />
                        </div>
                    </div>

                    {/* Item 2: Image Left, Text Right (Order Swap) */}
                    <div className="grid lg:grid-cols-2 gap-16 items-center">
                        <div className="order-2 lg:order-1 relative">
                            <div className="absolute -inset-4 bg-sky-100 transform -rotate-2 rounded-2xl"></div>
                            <img
                                src="https://picsum.photos/seed/global_service_v3/800/600"
                                alt="Global Service"
                                className="relative rounded-xl shadow-xl w-full"
                            />
                        </div>
                        <div className="order-1 lg:order-2">
                            <p className="text-sky-700 font-semibold uppercase tracking-widest text-sm mb-2">Global Support</p>
                            <h3 className="text-3xl font-bold text-slate-900 mb-6">Worldwide Service Network</h3>
                            <p className="text-lg text-slate-500 mb-8 leading-relaxed">
                                With distribution partners in over 50 countries, you're never far from expert support. Our 24/7 remote diagnostics platform allows us to troubleshoot issues before they impact your production.
                            </p>
                            <ul className="space-y-4">
                                {['24/7 Remote Monitoring', 'Local Service Partners', 'Genuine Spare Parts', '5-Year Warranty Program'].map((item, i) => (
                                    <li key={i} className="flex items-center gap-3">
                                        <CheckCircle className="w-5 h-5 text-sky-600 flex-shrink-0" />
                                        <span className="text-slate-700">{item}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* TRUST LOGOS - Template: stats.md > Logo Grid (Partners) */}
            {/* ------------------------------------------------------------------ */}
            <section className="py-16 bg-white border-t border-slate-100">
                <p className="text-center text-slate-400 text-sm tracking-widest uppercase mb-10">Trusted by Industry Leaders</p>
                <div className="flex flex-wrap justify-center gap-10 md:gap-16 px-6 opacity-60 grayscale hover:grayscale-0 hover:opacity-100 transition-all duration-500">
                    {/* Placeholder logos - replace with actual client logos */}
                    {['Partner A', 'Partner B', 'Partner C', 'Partner D', 'Partner E'].map((name, i) => (
                        <div key={i} className="h-10 px-6 bg-slate-100 rounded flex items-center justify-center text-slate-500 font-semibold text-sm">
                            {name}
                        </div>
                    ))}
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* CONTACT - Standard B2B Contact Section */}
            {/* ------------------------------------------------------------------ */}
            <section id="contact" className="py-20 bg-slate-900 text-white">
                <div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-16">
                    <div>
                        <p className="text-sky-400 font-semibold uppercase tracking-widest text-sm mb-2">Get in Touch</p>
                        <h2 className="text-4xl font-bold mb-6">Ready to Upgrade Your Production?</h2>
                        <p className="text-white/70 mb-10 leading-relaxed">
                            Contact our team for a consultation. We'll help you find the perfect CNC solution for your unique manufacturing requirements.
                        </p>

                        <div className="space-y-6">
                            <div className="flex items-start gap-4 group cursor-pointer">
                                <div className="w-12 h-12 bg-slate-800 group-hover:bg-sky-700 flex items-center justify-center transition-colors rounded">
                                    <MapPin className="w-5 h-5 text-sky-400 group-hover:text-white" />
                                </div>
                                <div className="pt-1">
                                    <p className="font-semibold text-white">Headquarters</p>
                                    <p className="text-white/60">No. 6, Ln. 476, Sec. 3, Sanfeng Rd., Fengyuan Dist., Taichung, Taiwan</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-4 group cursor-pointer">
                                <div className="w-12 h-12 bg-slate-800 group-hover:bg-sky-700 flex items-center justify-center transition-colors rounded">
                                    <Phone className="w-5 h-5 text-sky-400 group-hover:text-white" />
                                </div>
                                <div className="pt-1">
                                    <p className="font-semibold text-white">Phone</p>
                                    <p className="text-white/60">+886-4-2562-4226</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-4 group cursor-pointer">
                                <div className="w-12 h-12 bg-slate-800 group-hover:bg-sky-700 flex items-center justify-center transition-colors rounded">
                                    <Mail className="w-5 h-5 text-sky-400 group-hover:text-white" />
                                </div>
                                <div className="pt-1">
                                    <p className="font-semibold text-white">Email</p>
                                    <p className="text-white/60">info@topone-m.com</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="bg-slate-800 p-8 md:p-10 rounded-lg">
                        <form className="space-y-5">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                                <input type="text" placeholder="Your Name" className="w-full bg-slate-700 border border-slate-600 px-4 py-3 text-white placeholder-slate-400 focus:border-sky-500 focus:outline-none transition-colors rounded" />
                                <input type="email" placeholder="Email Address" className="w-full bg-slate-700 border border-slate-600 px-4 py-3 text-white placeholder-slate-400 focus:border-sky-500 focus:outline-none transition-colors rounded" />
                            </div>
                            <input type="text" placeholder="Company Name" className="w-full bg-slate-700 border border-slate-600 px-4 py-3 text-white placeholder-slate-400 focus:border-sky-500 focus:outline-none transition-colors rounded" />
                            <textarea placeholder="Your Message" rows={5} className="w-full bg-slate-700 border border-slate-600 px-4 py-3 text-white placeholder-slate-400 focus:border-sky-500 focus:outline-none transition-colors resize-none rounded"></textarea>
                            <button type="submit" className="w-full bg-sky-700 hover:bg-sky-600 text-white px-8 py-4 font-bold rounded transition-colors cursor-pointer">
                                Send Inquiry
                            </button>
                        </form>
                    </div>
                </div>
            </section>

            {/* ------------------------------------------------------------------ */}
            {/* FOOTER */}
            {/* ------------------------------------------------------------------ */}
            <footer className="bg-slate-950 text-slate-400 pt-16 pb-8">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-10 mb-12">
                        <div className="md:col-span-2">
                            <div className="flex items-center gap-3 mb-4">
                                <div className="w-10 h-10 bg-sky-700 text-white flex items-center justify-center font-bold rounded">T1</div>
                                <span className="text-xl font-bold text-white">TOP-ONE</span>
                            </div>
                            <p className="text-slate-500 max-w-sm">
                                Taiwan's premier CNC machining center manufacturer. Precision engineered since 1988.
                            </p>
                        </div>
                        <div>
                            <h5 className="text-white font-semibold mb-4">Quick Links</h5>
                            <ul className="space-y-2 text-sm">
                                {['Products', 'Features', 'About Us', 'Careers', 'Support'].map(link => (
                                    <li key={link}><a href="#" className="hover:text-sky-400 transition-colors cursor-pointer">{link}</a></li>
                                ))}
                            </ul>
                        </div>
                        <div>
                            <h5 className="text-white font-semibold mb-4">Follow Us</h5>
                            <ul className="space-y-2 text-sm">
                                {['LinkedIn', 'YouTube', 'Facebook'].map(link => (
                                    <li key={link}><a href="#" className="hover:text-sky-400 transition-colors cursor-pointer">{link}</a></li>
                                ))}
                            </ul>
                        </div>
                    </div>
                    <div className="border-t border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center text-xs">
                        <div className="flex gap-6">
                            <a href="#" className="hover:text-white transition-colors cursor-pointer">Privacy Policy</a>
                            <a href="#" className="hover:text-white transition-colors cursor-pointer">Terms of Service</a>
                        </div>
                        <div className="mt-4 md:mt-0 text-slate-500">
                            © 2026 TOP-ONE MACHINERY CO., LTD. All rights reserved.
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    );
}
