// lib/styles-data.ts
export interface StyleData {
  id: number;
  slug: string;
  name: string;
  type: 'General' | 'Landing Page' | 'BI/Analytics';
  keywords: string[];
  primaryColors: string[];
  description: string;
  bestFor: string[];
  complexity: 'Low' | 'Medium' | 'High';
  accessibility: string;
  implemented: boolean;
  usedSkill: boolean; // 是否使用 ui-ux-pro-max skill 製作
}

export const STYLES_DATABASE: StyleData[] = [
  {
    id: 1,
    slug: 'glassmorphism',
    name: 'Glassmorphism',
    type: 'General',
    keywords: ['frosted glass', 'transparent', 'layered', 'vibrant'],
    primaryColors: ['rgba(255,255,255,0.1)', 'rgba(255,255,255,0.3)'],
    description: 'Frosted glass effect with transparent layers and vibrant backgrounds',
    bestFor: ['Modern SaaS', 'Financial dashboards', 'Lifestyle apps'],
    complexity: 'Medium',
    accessibility: '⚠ Ensure 4.5:1 contrast',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 2,
    slug: 'neumorphism',
    name: 'Neumorphism',
    type: 'General',
    keywords: ['soft UI', 'embossed', 'rounded', 'monochromatic'],
    primaryColors: ['#C8E0F4', '#F5E0E8'],
    description: 'Soft UI with embossed elements and subtle shadows',
    bestFor: ['Health/wellness apps', 'Meditation platforms'],
    complexity: 'Medium',
    accessibility: '⚠ Low contrast',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 3,
    slug: 'brutalism',
    name: 'Brutalism',
    type: 'General',
    keywords: ['raw', 'unpolished', 'stark', 'high contrast'],
    primaryColors: ['#FF0000', '#0000FF', '#FFFF00'],
    description: 'Raw, unpolished design with stark contrasts',
    bestFor: ['Design portfolios', 'Artistic projects'],
    complexity: 'Low',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 4,
    slug: 'dark-mode',
    name: 'Dark Mode (OLED)',
    type: 'General',
    keywords: ['dark theme', 'low light', 'high contrast'],
    primaryColors: ['#000000', '#121212', '#0A0E27'],
    description: 'Dark theme optimized for OLED screens',
    bestFor: ['Night-mode apps', 'Coding platforms'],
    complexity: 'Low',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 5,
    slug: 'claymorphism',
    name: 'Claymorphism',
    type: 'General',
    keywords: ['soft 3D', 'chunky', 'playful', 'toy-like'],
    primaryColors: ['#FDBCB4', '#ADD8E6', '#98FF98'],
    description: 'Soft 3D appearance with chunky, toy-like elements',
    bestFor: ['Educational apps', "Children's apps", 'SaaS'],
    complexity: 'Medium',
    accessibility: '⚠ Ensure 4.5:1',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 6,
    slug: 'aurora-ui',
    name: 'Aurora UI',
    type: 'General',
    keywords: ['vibrant gradients', 'Northern Lights effect'],
    primaryColors: ['#0080FF', '#FF1493', '#00FFFF'],
    description: 'Vibrant gradients inspired by Northern Lights',
    bestFor: ['Modern SaaS', 'Creative agencies', 'Branding'],
    complexity: 'Medium',
    accessibility: '⚠ Text contrast',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 7,
    slug: 'cyberpunk',
    name: 'Cyberpunk UI',
    type: 'General',
    keywords: ['neon', 'dark mode', 'terminal', 'HUD', 'sci-fi'],
    primaryColors: ['#00FF00', '#FF00FF', '#00FFFF'],
    description: 'Neon-lit dark interface with sci-fi aesthetics',
    bestFor: ['Gaming platforms', 'Tech products', 'Crypto'],
    complexity: 'Medium',
    accessibility: '⚠ Limited (dark+neon)',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 8,
    slug: 'neubrutalism',
    name: 'Neubrutalism',
    type: 'General',
    keywords: ['bold borders', 'black outlines', '45° shadows'],
    primaryColors: ['#FFEB3B', '#FF5252', '#2196F3', '#000000'],
    description: 'Bold borders with hard shadows and vibrant colors',
    bestFor: ['Gen Z brands', 'Startups', 'Creative agencies'],
    complexity: 'Low',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 9,
    slug: 'bento-grid',
    name: 'Bento Box Grid',
    type: 'General',
    keywords: ['modular cards', 'asymmetric grid', 'Apple-style'],
    primaryColors: ['#FFFFFF', '#F5F5F5'],
    description: 'Modular card layout inspired by Apple design',
    bestFor: ['Dashboards', 'Product pages', 'Portfolios'],
    complexity: 'Low',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 10,
    slug: 'liquid-glass',
    name: 'Liquid Glass',
    type: 'General',
    keywords: ['flowing glass', 'morphing', 'smooth transitions'],
    primaryColors: ['Vibrant iridescent (rainbow spectrum)'],
    description: 'Flowing glass effect with morphing transitions',
    bestFor: ['Premium SaaS', 'High-end e-commerce'],
    complexity: 'High',
    accessibility: '⚠ Text contrast',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 11,
    slug: 'corporate-blue',
    name: 'Corporate Blue',
    type: 'Landing Page',
    keywords: ['corporate', 'professional', 'trust', 'blue', 'business'],
    primaryColors: ['#1E3A8A', '#3B82F6', '#DBEAFE'],
    description: '專業企業風格，藍/紫色調搭配信任徽章與流程圖示',
    bestFor: ['清潔服務', 'IT 公司', '顧問公司', '金融服務'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 12,
    slug: 'service-pro',
    name: 'Service Pro',
    type: 'Landing Page',
    keywords: ['service', 'repair', 'orange', 'teal', 'professional'],
    primaryColors: ['#F97316', '#14B8A6', '#FFFFFF'],
    description: '服務導向版型，橘/綠強調色，圖文交錯，FAQ 與團隊展示',
    bestFor: ['維修服務', '冷氣工程', '居家服務', '技術服務'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 13,
    slug: 'property-showcase',
    name: 'Property Showcase',
    type: 'Landing Page',
    keywords: ['real estate', 'property', 'search', 'listings', 'purple'],
    primaryColors: ['#6366F1', '#8B5CF6', '#F8FAFC'],
    description: '房地產風格，搜尋框+分類選單，物件卡片含價格與規格',
    bestFor: ['房地產', '租屋平台', '建設公司', '仲介'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 14,
    slug: 'industrial-red',
    name: 'Industrial Red',
    type: 'Landing Page',
    keywords: ['industrial', 'red', 'black', 'bold', 'diagonal'],
    primaryColors: ['#DC2626', '#000000', '#FFFFFF'],
    description: '紅黑工業風，斜切設計元素，強烈對比與視覺衝擊',
    bestFor: ['電機工程', '製造業', '工業服務', '營建業'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 15,
    slug: 'japanese-corporate',
    name: 'Japanese Corporate',
    type: 'Landing Page',
    keywords: ['japanese', 'minimal', 'clean', 'corporate', 'navy'],
    primaryColors: ['#1E3A5F', '#FFFFFF', '#F5F5F5'],
    description: '日式企業極簡風，產品分類搜尋，技術文章，企業藍',
    bestFor: ['精密工具', '零件製造', '工業設備', 'B2B 企業'],
    complexity: 'Low',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 16,
    slug: 'navy-industrial',
    name: 'Navy Industrial',
    type: 'Landing Page',
    keywords: ['navy', 'industrial', 'full-width', 'japanese', 'wood'],
    primaryColors: ['#1E3856', '#FFFFFF', '#F5F5F5'],
    description: '深藍工業風，全幅大圖、歷史感、大字排版',
    bestFor: ['製造業', '木材業', '傳統產業', '工廠'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 17,
    slug: 'it-corporate',
    name: 'IT Corporate',
    type: 'Landing Page',
    keywords: ['IT', 'corporate', 'blue', 'diagonal', 'business'],
    primaryColors: ['#2563EB', '#E0E7FF', '#FFFFFF'],
    description: 'IT 企業風，斜角圖片排版、商務藍、事業案內',
    bestFor: ['IT 公司', '系統整合', '軟體公司', 'SI'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 18,
    slug: 'mint-tech',
    name: 'Mint Tech',
    type: 'Landing Page',
    keywords: ['mint', 'teal', 'tech', 'clean', 'geometric'],
    primaryColors: ['#14B8A6', '#10B981', '#FFFFFF'],
    description: '薄荷科技風，幾何裝飾、乾淨白底、招募頁面',
    bestFor: ['電氣設備', '工程公司', '技術服務', '人才招募'],
    complexity: 'Low',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 19,
    slug: 'materials-grid',
    name: 'Materials Grid',
    type: 'Landing Page',
    keywords: ['materials', 'grid', 'search', 'showroom', 'tech'],
    primaryColors: ['#3B82F6', '#1E40AF', '#F8FAFC'],
    description: '材料/解決方案網格，搜尋+分類、數位展廳、產業應用',
    bestFor: ['材料商', '化學公司', '複合材料', 'B2B'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 20,
    slug: 'esg-corporate',
    name: 'ESG Corporate',
    type: 'Landing Page',
    keywords: ['ESG', 'sustainability', 'corporate', 'fullwidth', 'hero'],
    primaryColors: ['#1E3A5F', '#059669', '#F0FDF4'],
    description: 'ESG 企業風，全幅影片 Hero、永續經營區塊、IR 新聞',
    bestFor: ['上市公司', '集團企業', '永續報告', '投資人關係'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: false,
  },
  {
    id: 21,
    slug: 'soft-ui-evolution',
    name: 'Soft UI Evolution',
    type: 'Landing Page',
    keywords: ['soft ui', 'neumorphism', 'pink', 'spa', 'beauty', 'elegant', 'skill'],
    primaryColors: ['#EC4899', '#8B5CF6', '#FDF2F8'],
    description: '【🤖 Skill 生成】進化版 Soft UI，粉紫配色，Playfair Display 字體',
    bestFor: ['SPA', '美容', '健康', '奢華品牌'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA+',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 22,
    slug: 'industrial-pro',
    name: 'Industrial Pro',
    type: 'Landing Page',
    keywords: ['industrial', 'manufacturing', 'B2B', 'trust', 'professional', 'skill'],
    primaryColors: ['#0F172A', '#0369A1', '#F8FAFC'],
    description: '【🤖 Skill 生成】Trust & Authority 風格，深藍專業配色，Plus Jakarta Sans 字體',
    bestFor: ['製造業', '工業設備', '自動化', 'B2B 企業'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 23,
    slug: 'gourmet-bistro',
    name: 'Gourmet Bistro',
    type: 'Landing Page',
    keywords: ['restaurant', 'food', 'dining', 'elegant', 'culinary', 'skill'],
    primaryColors: ['#1C1412', '#D4AF37', '#231917'],
    description: '【🤖 Skill 生成】Dark & Luxe 風格，深褐金配色，Cormorant Garamond + Karla 字體',
    bestFor: ['餐廳', '高級料理', '法式餐廳', 'Fine Dining'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 24,
    slug: 'secure-bank',
    name: 'SecureBank',
    type: 'Landing Page',
    keywords: ['fintech', 'banking', 'finance', 'trust', 'security', 'skill'],
    primaryColors: ['#1E3A8A', '#FBBF24', '#F8FAFC'],
    description: '【🤖 Skill 生成】Trust & Authority 風格，海軍藍金配色，IBM Plex Sans 字體',
    bestFor: ['銀行', '金融', '保險', 'Fintech'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 25,
    slug: 'fit-studio',
    name: 'FitStudio',
    type: 'Landing Page',
    keywords: ['fitness', 'gym', 'health', 'workout', 'training', 'skill'],
    primaryColors: ['#0A0A0A', '#FF6B35', '#FFFFFF'],
    description: '【🤖 Skill 生成】Dark & Dynamic 風格，黑橘配色，Space Grotesk 字體',
    bestFor: ['健身房', '運動中心', '瑜伽教室', '個人訓練'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 26,
    slug: 'moderna-gallery',
    name: 'Moderna Gallery',
    type: 'Landing Page',
    keywords: ['art', 'gallery', 'museum', 'exhibition', 'culture', 'skill'],
    primaryColors: ['#0D0D0D', '#FAFAFA', '#FFFFFF'],
    description: '【🤖 Skill 生成】Minimalist & Elegant 風格，黑白極簡，Playfair Display + DM Sans 字體',
    bestFor: ['藝廊', '美術館', '展覽空間', '藝術機構'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 27,
    slug: 'wanderlust-travel',
    name: 'Wanderlust Travel',
    type: 'Landing Page',
    keywords: ['travel', 'tourism', 'vacation', 'destination', 'adventure', 'skill'],
    primaryColors: ['#1E293B', '#2563EB', '#F7F6F3'],
    description: '【🤖 Skill 生成】Immersive & Inspiring 風格，藍灰配色，Plus Jakarta Sans 字體',
    bestFor: ['旅行社', '觀光業', '旅遊平台', '度假村'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 28,
    slug: 'cnc-machine',
    name: 'PrecisionCNC',
    type: 'Landing Page',
    keywords: ['cnc', 'machine tool', 'manufacturing', 'industrial', 'B2B', 'skill'],
    primaryColors: ['#1A1A1A', '#F59E0B', '#F5F5F5'],
    description: '【🤖 Skill 生成】Industrial Minimalism 風格，深灰琥珀配色，Barlow 字體',
    bestFor: ['工具機', 'CNC 製造', '精密加工', 'B2B 外銷'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 29,
    slug: 'automation-systems',
    name: 'AutoSystems',
    type: 'Landing Page',
    keywords: ['automation', 'industrial', 'factory', 'robotics', 'B2B', 'skill'],
    primaryColors: ['#0C4A6E', '#06B6D4', '#FFFFFF'],
    description: '【🤖 Skill 生成】Tech Corporate 風格，海軍藍霓虹配色，Outfit 字體',
    bestFor: ['工業自動化', '機械手臂', '智慧製造', 'B2B 企業'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 30,
    slug: 'electronics-components',
    name: 'ElecParts',
    type: 'Landing Page',
    keywords: ['electronics', 'components', 'semiconductor', 'B2B', 'catalog', 'skill'],
    primaryColors: ['#1E293B', '#10B981', '#F8FAFC'],
    description: '【🤖 Skill 生成】Clean Tech 風格，深藍電光綠配色，IBM Plex Sans 字體',
    bestFor: ['電子零組件', '半導體', '連接器', 'B2B 外銷'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
  {
    id: 31,
    slug: 'medical-equipment',
    name: 'MediCare',
    type: 'Landing Page',
    keywords: ['medical', 'healthcare', 'equipment', 'hospital', 'compliance', 'skill'],
    primaryColors: ['#0369A1', '#059669', '#FFFFFF'],
    description: '【🤖 Skill 生成】Clean Healthcare 風格，醫療藍信任綠配色，Plus Jakarta Sans 字體',
    bestFor: ['醫療器材', '呼吸治療', '生理監測', '醫院設備'],
    complexity: 'Medium',
    accessibility: '✓ WCAG AAA',
    implemented: true,
    usedSkill: true, // ✅ 使用 ui-ux-pro-max skill 製作
  },
];

export function getStyleBySlug(slug: string): StyleData | undefined {
  return STYLES_DATABASE.find(style => style.slug === slug);
}

export function getImplementedStyles(): StyleData[] {
  return STYLES_DATABASE.filter(style => style.implemented);
}

export function getStylesByType(type: StyleData['type']): StyleData[] {
  return STYLES_DATABASE.filter(style => style.type === type);
}

export function getSkillStyles(): StyleData[] {
  return STYLES_DATABASE.filter(style => style.usedSkill);
}

export function getNonSkillStyles(): StyleData[] {
  return STYLES_DATABASE.filter(style => !style.usedSkill);
}
